### ISSUE TITLE
Drop react-redux, use own bindings to redux

### ISSUE THREAD

**Issue by ognen** [netceteragroup/girders-elements#17]
React-redux's view over the state is complicating (and adding overhead) over Element's simple tree walking routine. 

Each connected component is allowed to "see" anything in the state. This complicates the shouldComponentUpdate scheme: internally react-redux [has to trigger a re-evaluation of every connected component's selector](https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L197) to make sure everything is up to date. This simply nullifies any performance benefit we intend to harness via the use of Immutable and our stricter architecture (the props of an element being always a node in the tree).

Kudos go to @oliverlaz for the tip.

**Comment by andon** [comment]
We have 2 places where we connect (subscribe) to changes:
* in the root element: https://github.com/netceteragroup/girders-elements/blob/develop/src/boot/engine.js#L32
* in every registered element: https://github.com/netceteragroup/girders-elements/blob/develop/src/ui/uiRegistry.js#L48

The second usage is not needed at all. The following PR:
https://github.com/netceteragroup/girders-elements/pull/18
will remove it and take the dispatch from context. That was the sole reason why it was used here.

The first usage is still needed as in our architecture (singe-state-atom), each change will trigger change of the root element. We can most probably subscribe to the store manually instead of using redux-react.

**Comment by ognen** [comment]
- boot/Engine is deprecated. egine/engine.js is the thgin.
- engine/engine.js needs to be changed to handle store changes.  (See comments on #18).
- also, drop the dependency in package.json

**Comment by andon** [comment]
I've implemented the remaining changes:
https://github.com/netceteragroup/girders-elements/commit/80918e790a760b1f5b96d9adebe86253624ec470
