### ISSUE TITLE
Fix .babelrc

### ISSUE THREAD

**Issue by ognen** [netceteragroup/girders-elements#7]
See [developer guidelines](https://github.com/netceteragroup/girders-elements/wiki/Developer-Guidelines)

**Comment by andon** [comment]
Yes, this should be fixed, but just to give a context why this is at the moment.

The library is used in react-native project. In react-native, there are many issues reported in case you have .babelrc file present in your project dependencies. The main discussion is here:
https://github.com/facebook/react-native/issues/4062

This has led that most of the project in the eco-system are not publishing .babelrc (either by npm ignoring it, or by opting in what will be included on npm publish). I can verify this. On the react-native project I'm currently on, that are a number of dependencies. But, there is not a single .babelrc, except:
* one on project root level (that has been included in recent version of react-native templates, because of issues).
* one in this module (at the moment I'm using this project as a git-submodule, so npm ignoring it does not help).

There are proposals where this is headed here:
https://github.com/facebook/react-native/issues/10966

**Comment by ognen** [comment]
- switched to react-native preset
- with #33 .babelrc is now in the top-level package and will not be included with the other packages
