### ISSUE TITLE
Issue with Object.setPrototypeOf

### ISSUE THREAD

**Issue by mdimovska** [netceteragroup/girders-elements#97]
Object.setPrototypeOf is not allowed by default in React Native (there is not a babel preset for it) and this might be an issue in case the browser does not support it or the app does not have a polyfill for this.
https://github.com/facebook/react-native/blob/master/babel-preset/configs/main.js, https://facebook.github.io/react-native/docs/javascript-environment.html.

It is used only in one place in core - when instantiating a subsystem.

On Android, the following error appears (when not in debug mode):
![image](https://user-images.githubusercontent.com/6908242/35499599-662f31cc-04d3-11e8-929a-a9d1ca82226a.png)

**Comment by andon** [comment]
@mdimovska You are right. We use:
```
import 'core-js/modules/es6.object.set-prototype-of'
```
in our main `index.android.js`.

For a reference there is a babel plugin for it:
https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-object-set-prototype-of-to-assign

**Comment by ognen** [comment]
Hmm, @bevkoski I think we need to extend our README to include necessary polyfils for react native.

**Comment by mdimovska** [comment]
Another issue (on web apps) is the following (**regeneratorRuntime is not defined**):
![image](https://user-images.githubusercontent.com/6908242/35962144-b0151bb4-0cb0-11e8-9b58-95425e830f0d.png)
Doesn't happen on native, because there is already a corresponding plugin for this in babel-preset-react-native.

I am mentioning this here because it's also related to missing plugins/polyfills...

**Possible solution:**
Include the `regenerator-runtime` dependency (https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime) and import it in the main `index.js`:
`import 'regenerator-runtime/runtime'`

**Comment by bevkoski** [comment]
It seems that the simplest solution to both issues is to use [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/). It includes both the `core-js` polyfills that @andon mentioned and the regenerator runtime that @mdimovska found out about.

A more conservative solution would be to import `regenerator-runtime`, `set-prototype-of`, but also `symbol` (since [it is used](https://github.com/netceteragroup/girders-elements/blob/master/packages/core/src/read/types.js#L44) for the read types) separately.

@ognen, I [added both approaches](https://github.com/netceteragroup/girders-elements/pull/96/commits/6085c815699f2fc11afa0d81f3c365b7f45bc3d1) to the README.

**Comment by ognen** [comment]
Yes, that's the simplest solution but it carries a big cost on startup time (the polypill is big). Listing just the stuff we need is advantageous for people wanting to optimize.
